/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface KnSideDrawer {
    'open': boolean;
    'title': string;
  }
  interface KnSideDrawerAttributes extends StencilHTMLAttributes {
    'open'?: boolean;
    'title'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'KnSideDrawer': Components.KnSideDrawer;
  }

  interface StencilIntrinsicElements {
    'kn-side-drawer': Components.KnSideDrawerAttributes;
  }


  interface HTMLKnSideDrawerElement extends Components.KnSideDrawer, HTMLStencilElement {}
  var HTMLKnSideDrawerElement: {
    prototype: HTMLKnSideDrawerElement;
    new (): HTMLKnSideDrawerElement;
  };

  interface HTMLElementTagNameMap {
    'kn-side-drawer': HTMLKnSideDrawerElement
  }

  interface ElementTagNameMap {
    'kn-side-drawer': HTMLKnSideDrawerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
