/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface KnLoading {}
  interface KnLoadingAttributes extends StencilHTMLAttributes {}

  interface KnStockFinder {}
  interface KnStockFinderAttributes extends StencilHTMLAttributes {
    'onKnSymbolSelected'?: (event: CustomEvent<string>) => void;
  }

  interface KnStockPrice {
    'stockSymbol': string;
  }
  interface KnStockPriceAttributes extends StencilHTMLAttributes {
    'stockSymbol'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'KnLoading': Components.KnLoading;
    'KnStockFinder': Components.KnStockFinder;
    'KnStockPrice': Components.KnStockPrice;
  }

  interface StencilIntrinsicElements {
    'kn-loading': Components.KnLoadingAttributes;
    'kn-stock-finder': Components.KnStockFinderAttributes;
    'kn-stock-price': Components.KnStockPriceAttributes;
  }


  interface HTMLKnLoadingElement extends Components.KnLoading, HTMLStencilElement {}
  var HTMLKnLoadingElement: {
    prototype: HTMLKnLoadingElement;
    new (): HTMLKnLoadingElement;
  };

  interface HTMLKnStockFinderElement extends Components.KnStockFinder, HTMLStencilElement {}
  var HTMLKnStockFinderElement: {
    prototype: HTMLKnStockFinderElement;
    new (): HTMLKnStockFinderElement;
  };

  interface HTMLKnStockPriceElement extends Components.KnStockPrice, HTMLStencilElement {}
  var HTMLKnStockPriceElement: {
    prototype: HTMLKnStockPriceElement;
    new (): HTMLKnStockPriceElement;
  };

  interface HTMLElementTagNameMap {
    'kn-loading': HTMLKnLoadingElement
    'kn-stock-finder': HTMLKnStockFinderElement
    'kn-stock-price': HTMLKnStockPriceElement
  }

  interface ElementTagNameMap {
    'kn-loading': HTMLKnLoadingElement;
    'kn-stock-finder': HTMLKnStockFinderElement;
    'kn-stock-price': HTMLKnStockPriceElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
